<?php
vc_map( 
	array( 
		'base' => 'dh_animation', 
		"category" => __( "Sitesao", 'luxury-wp' ), 
		'name' => __( 'Animation Box', 'luxury-wp' ), 
		'description' => __( 'Enable animation for serveral elements.', 'luxury-wp' ), 
		'as_parent' => array( 'only' => 'vc_column_text,dh_button,dh_lists,vc_empty_space,vc_separator,dh_iconbox,dh_member,vc_custom_heading,vc_cta_button,vc_button,vc_pie,vc_message,vc_single_image,vc_gmaps,vc_raw_html,vc_icon' ), 
		'content_element' => true, 
		'class' => 'dh-vc-element dh-vc-element-animation', 
		'icon' => 'dh-vc-icon-animation', 
		'js_view' => 'VcColumnView', 
		'show_settings_on_create' => true, 
		'params' => array( 
			array( 
				'param_name' => 'animation', 
				'heading' => __( 'Select Animation', 'luxury-wp' ), 
				'description' => __( 'Choose animation effect for this column.', 'luxury-wp' ), 
				'type' => 'dropdown', 
				'std' => 'fadeIn', 
				'value' => array( 
					"None" => "", 
					"Flash" => "flash", 
					"Shake" => "shake", 
					"Bounce" => "bounce", 
					"Fade In" => "fadeIn", 
					"Fade In Up" => "fadeInUp", 
					"Fade In Down" => "fadeInDown", 
					"Fade In Left" => "fadeInLeft", 
					"Fade In Right" => "fadeInRight", 
					"Fade In Up Big" => "fadeInUpBig", 
					"Fade In Down Big" => 'fadeInDownBig', 
					'Fade In Left Big' => 'fadeInLeftBig', 
					'Fade In Right Big' => 'fadeInRightBig', 
					'Fade Out' => 'fadeOut', 
					'Fade Out Up' => 'fadeOutUp', 
					'Fade Out Down' => 'fadeOutDown', 
					'Fade Out Left' => 'fadeOutLeft', 
					'Fade Out Right' => 'fadeOutRight', 
					'Fade Out Up Big' => 'fadeOutUpBig', 
					'Fade Out Down Big' => 'fadeOutDownBig', 
					'Fade Out Left Big' => 'fadeOutLeftBig', 
					'Fade Out Right Big' => 'fadeOutRightBig', 
					'Slide In Down' => 'slideInDown', 
					'Slide In Left' => 'slideInLeft', 
					'Slide In Right' => 'slideInRight', 
					'Slide Out Up' => 'slideOutUp', 
					'Slide Out Left' => 'slideOutLeft', 
					'Slide Out Right' => 'slideOutRight', 
					'Bounce In' => 'bounceIn', 
					'Bounce In Up' => 'bounceInUp', 
					'Bounce In Down' => 'bounceInDown', 
					'Bounce In Left' => 'bounceInLeft', 
					'Bounce In Right' => 'bounceInRight', 
					'Bounce Out' => 'bounceOut', 
					'Bounce Out Up' => 'bounceOutUp', 
					'Bounce Out Down' => 'bounceOutDown', 
					'Bounce Out Left' => 'bounceOutLeft', 
					'Bounce Out Right' => 'bounceOutRight', 
					'Light Speed In' => 'lightSpeedIn', 
					'Light Speed Out' => 'lightSpeedOut' ) ), 
			
			array( 
				"type" => "dropdown", 
				"heading" => __( "Animation Transition", 'luxury-wp' ), 
				"param_name" => "animation_timing", 
				'std' => 'linear', 
				"value" => array( 
					'linear' => 'linear', 
					'ease' => 'ease', 
					'easeIn' => 'easeIn', 
					'easeOut' => 'easeOut', 
					'easeInOut' => 'easeInOut', 
					'easeInQuad' => 'easeInQuad', 
					'easeInCubic' => 'easeInCubic', 
					'easeInQuart' => 'easeInQuart', 
					'easeInQuint' => 'easeInQuint', 
					'easeInSine' => 'easeInSine', 
					'easeInExpo' => 'easeInExpo', 
					'easeInCirc' => 'easeInCirc', 
					'easeInBack' => 'easeInBack', 
					'easeOutQuad' => 'easeOutQuad', 
					'easeOutCubic' => 'easeOutCubic', 
					'easeOutQuart' => 'easeOutQuart', 
					'easeOutQuint' => 'easeOutQuint', 
					'easeOutSine' => 'easeOutSine', 
					'easeOutExpo' => 'easeOutExpo', 
					'easeOutCirc' => 'easeOutCirc', 
					'easeOutBack' => 'easeOutBack', 
					'easeInOutQuad' => 'easeInOutQuad', 
					'easeInOutCubic' => 'easeInOutCubic', 
					'easeInOutQuart' => 'easeInOutQuart', 
					'easeInOutQuint' => 'easeInOutQuint', 
					'easeInOutSine' => 'easeInOutSine', 
					'easeInOutExpo' => 'easeInOutExpo', 
					'easeInOutCirc' => 'easeInOutCirc', 
					'easeInOutBack' => 'easeInOutBack' ), 
				"description" => __( "Select the a animation transition.", 'luxury-wp' ) ), 
			array( 
				'param_name' => 'animation_duration', 
				'heading' => __( 'Animation Duration (ms)', 'luxury-wp' ), 
				'description' => __( 'Specifies how many milliseconds an animation takes to complete.', 'luxury-wp' ), 
				'type' => 'ui_slider', 
				'value' => '1000', 
				'data_min' => '0', 
				'data_max' => '3000', 
				'data_step' => '50', 
				'dependency' => array( 'element' => "animation", 'not_empty' => true ) ), 
			array( 
				'param_name' => 'animation_delay', 
				'heading' => __( 'Animation Delay (ms)', 'luxury-wp' ), 
				'description' => __( 'Specifies a delay before the animation will start.', 'luxury-wp' ), 
				'type' => 'ui_slider', 
				'value' => '0', 
				'data_min' => '0', 
				'data_max' => '3000', 
				'data_step' => '50', 
				'dependency' => array( 'element' => "animation", 'not_empty' => true ) ), 
			array( 
				'param_name' => 'visibility', 
				'heading' => __( 'Visibility', 'luxury-wp' ), 
				'type' => 'dropdown', 
				'std' => 'all', 
				'value' => array( 
					__( 'All Devices', 'luxury-wp' ) => "all", 
					__( 'Hidden Phone', 'luxury-wp' ) => "hidden-phone", 
					__( 'Hidden Tablet', 'luxury-wp' ) => "hidden-tablet", 
					__( 'Hidden PC', 'luxury-wp' ) => "hidden-pc", 
					__( 'Visible Phone', 'luxury-wp' ) => "visible-phone", 
					__( 'Visible Tablet', 'luxury-wp' ) => "visible-tablet", 
					__( 'Visible PC', 'luxury-wp' ) => "visible-pc" ) ), 
			array( 
				'param_name' => 'el_class', 
				'heading' => __( '(Optional) Extra class name', 'luxury-wp' ), 
				'type' => 'textfield', 
				'value' => '', 
				"description" => __( 
					"If you wish to style particular content element differently, then use this field to add a class name and then refer to it in your css file.", 
					'luxury-wp' ) ), 
			array( 
				'type' => 'css_editor', 
				'heading' => __( 'Css', 'luxury-wp' ), 
				'param_name' => 'css', 
				'group' => __( 'Design options', 'luxury-wp' ) ) ) ) );

class WPBakeryShortCode_DH_Animation extends DHWPBakeryShortcodeContainer {
}
